### ISSUE TITLE
Rune Audio Error

### ISSUE THREAD

**Issue by Roughtrade** [antiprism/mpd_oled#2]
[root@RuneAudio cava]# ./autogen.sh
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
[root@RuneAudio cava]# CC=clang ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... no
checking whether make supports nested variables... no
checking for style of include used by make... none
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/root/cava':
configure: error: C compiler cannot create executables
See `config.log' for more details
[root@RuneAudio cava]# make
make: error while loading shared libraries: libguile-2.2.so.1: cannot open shared object file: No such file or directory

Any Idea
Regards Peter

**Comment by antiprism** [comment]
Hi Peter

Is Clang actually installed? Try

```clang --version```

I found that the servers frequently timed out when trying to install packages on RuneAudio, and it took several attempts to get clang installed. If this is the case, rerun the package installation command until all the packages are installed.

Adrian.

**Comment by Roughtrade** [comment]
[root@RuneAudio cava]# clang --version
clang: error while loading shared libraries: libLLVM-6.0.so: cannot open shared object file: No such file or directory

:(

**Comment by antiprism** [comment]
When you rerun the package installation command does it indicate that all the packages are installed?
```
pacman -S autoconf automake clang make libtool fftw alsa-lib
```

**Comment by Roughtrade** [comment]
All Packages are installed

**Comment by antiprism** [comment]
It may not be the same on your system, but it looks like clang depends on llvm-libs, which installs libLLVM-6.0.so, and so these packages/dependencies may be broken on the version of RuneAudio you are using

https://www.archlinux.org/packages/extra/x86_64/clang/
https://www.archlinux.org/packages/extra/x86_64/llvm-libs/
https://www.archlinux.org/packages/extra/x86_64/llvm-libs/files/

I wrote the mpd_oled installation instructions to use Clang on RuneAudio because it was not possible for me to install a working GCC from packages, but I was able to install a working Clang. However, this doesn't seem to be the case for you, in which case you could try with GCC instead and see if that works
```
sudo pacman -S base-devel
```
Then, for cava, configure with
```
./configure
```
And for mpd_oled, build with
```
PLAYER=RUNEAUDIO make
```

**Comment by Roughtrade** [comment]
I think so. My personal Problem is the Kernel. I have to use a Kernel below 4.12 ( Kali reclocker & Piano Dac ) Amazing Sound !!  kali is only supported by these old Kernels.
I got it running on moode Audio and downgraded the kernel.
I will try it with rune Audio next weekend, i think you should close this issue. Thank you 

Best regards Peter
