### ISSUE TITLE
Is MPD_Oled compatible to Volumio snapcast plugin?

### ISSUE THREAD

**Issue by Korniman-the-Rooky** [antiprism/mpd_oled#44]
Dear Adrian, is MPD_Oled compatible to Volumio snapcast plugin for multi room solution?
Currently my Raspi pops up failure while activating the plugin and later on the volumio player has malfunction.
Thanx for your support
Benjamin

**Comment by antiprism** [comment]
Hi Benjamin

Did you set up the audio copy for mpd_oled like ths?
https://github.com/antiprism/mpd_oled/blob/master/INSTALL_VOLUMIO.md#configure-copy-of-audio

What is the error you get when you activate the snapcast plugin (it would help if you could include the exact text, copy and paste if possible). What happens when Volumio later malfunctions (what specifically is not working)?

Adrian.

**Comment by Korniman-the-Rooky** [comment]
Dear Adrian, I made a clean New Image with pure Volumio and activated only
snapcast plugin. It also did not work. So sorry for the trouble. I will
first try to fix the basics.
Thanx
Benjamin

Mit freundlichen Grüßen
Benjamin Korntheuer

Adrian Rossiter <notifications@github.com> schrieb am Mo., 29. Juni 2020,
19:50:

**Comment by antiprism** [comment]
Hi Benjamin

No problem. Thanks for letting me know!

Adrian.
