### ISSUE TITLE
Russian song titles are not displayed

### ISSUE THREAD

**Issue by dfyzicka** [antiprism/mpd_oled#83]
when playing tracks with Russian id tags instead of the name, the screen is empty, it can select a different font with support for Cyrillic characters, but I don’t understand how to do it

**Comment by dfyzicka** [comment]
i use volumio 3 and mpd_oled plugin

**Comment by antiprism** [comment]
Hi

mpd_oled only supports Latin alphabets (stripping any accents and printing ASCII), and I cannot help with changing this. See  issue https://github.com/antiprism/mpd_oled/issues/9 .

However, the development version of mpd_oled probably does support Cyrillic alphabets

   https://github.com/antiprism/mpd_oled_dev

Please note that there is no Volumio plugin for the development version, and the installation instructions will only produce a working spectrum display when MPD is the player (e.g. when playing audio files and radio streams), but the spectrum area will be blank when using other players, e.g. Spotify. Also, this is development code, and unsupported (although some people are currently using it because it supports more screen types than the release version of mpd_oled).

Adrian.

**Comment by dfyzicka** [comment]
Thank you in any case, what you did is very cool
